// ═══════════════════════════════════════════
// 网络拓扑图标品类 → 动态 import 映射（自动生成，勿手改）
// 生成: node scripts/gen-network-shapes.mjs --category network,network_cisco,network_aws,network_azure,network_aliyun
// 必须保持静态可分析（每个 value 一条字面量 import），vite 据此切成 46 个独立 chunk
// ═══════════════════════════════════════════
import type { ShapeDefinition } from '@/types'

export const NET_ICON_LOADERS: Record<string, () => Promise<ShapeDefinition[]>> = {
  "network": () => import('./groups/network').then((m) => m.shapes),
  "cisco_bulidings": () => import('./groups/cisco_bulidings').then((m) => m.shapes),
  "cisco_computers_peripherals": () => import('./groups/cisco_computers_peripherals').then((m) => m.shapes),
  "cisco_control_module": () => import('./groups/cisco_control_module').then((m) => m.shapes),
  "cisco_directors": () => import('./groups/cisco_directors').then((m) => m.shapes),
  "cisco_hubs_gateways": () => import('./groups/cisco_hubs_gateways').then((m) => m.shapes),
  "cisco_misc": () => import('./groups/cisco_misc').then((m) => m.shapes),
  "cisco_modems_phones": () => import('./groups/cisco_modems_phones').then((m) => m.shapes),
  "cisco_people": () => import('./groups/cisco_people').then((m) => m.shapes),
  "cisco_routers": () => import('./groups/cisco_routers').then((m) => m.shapes),
  "cisco_security": () => import('./groups/cisco_security').then((m) => m.shapes),
  "cisco_servers": () => import('./groups/cisco_servers').then((m) => m.shapes),
  "cisco_storage": () => import('./groups/cisco_storage').then((m) => m.shapes),
  "cisco_switches": () => import('./groups/cisco_switches').then((m) => m.shapes),
  "cisco_wireless": () => import('./groups/cisco_wireless').then((m) => m.shapes),
  "aws_analytics": () => import('./groups/aws_analytics').then((m) => m.shapes),
  "aws_app_servers": () => import('./groups/aws_app_servers').then((m) => m.shapes),
  "aws_compute": () => import('./groups/aws_compute').then((m) => m.shapes),
  "aws_database": () => import('./groups/aws_database').then((m) => m.shapes),
  "aws_devel_tools": () => import('./groups/aws_devel_tools').then((m) => m.shapes),
  "aws_enterprise_apps": () => import('./groups/aws_enterprise_apps').then((m) => m.shapes),
  "aws_general": () => import('./groups/aws_general').then((m) => m.shapes),
  "aws_iot": () => import('./groups/aws_iot').then((m) => m.shapes),
  "aws_mgmt_tools": () => import('./groups/aws_mgmt_tools').then((m) => m.shapes),
  "aws_mobile_servers": () => import('./groups/aws_mobile_servers').then((m) => m.shapes),
  "aws_networking": () => import('./groups/aws_networking').then((m) => m.shapes),
  "aws_sdk": () => import('./groups/aws_sdk').then((m) => m.shapes),
  "aws_security_identity": () => import('./groups/aws_security_identity').then((m) => m.shapes),
  "aws_storage": () => import('./groups/aws_storage').then((m) => m.shapes),
  "aws_workforce": () => import('./groups/aws_workforce').then((m) => m.shapes),
  "aws_groups": () => import('./groups/aws_groups').then((m) => m.shapes),
  "azure": () => import('./groups/azure').then((m) => m.shapes),
  "ali_app_service": () => import('./groups/ali_app_service').then((m) => m.shapes),
  "ali_database": () => import('./groups/ali_database').then((m) => m.shapes),
  "ali_devel_resource": () => import('./groups/ali_devel_resource').then((m) => m.shapes),
  "ali_domain_website": () => import('./groups/ali_domain_website').then((m) => m.shapes),
  "ali_elastic_calc": () => import('./groups/ali_elastic_calc').then((m) => m.shapes),
  "ali_industry_cloud": () => import('./groups/ali_industry_cloud').then((m) => m.shapes),
  "ali_internet_midd": () => import('./groups/ali_internet_midd').then((m) => m.shapes),
  "ali_large_scale_calc": () => import('./groups/ali_large_scale_calc').then((m) => m.shapes),
  "ali_manage_monitor": () => import('./groups/ali_manage_monitor').then((m) => m.shapes),
  "ali_mobile_service": () => import('./groups/ali_mobile_service').then((m) => m.shapes),
  "ali_network": () => import('./groups/ali_network').then((m) => m.shapes),
  "ali_other_products": () => import('./groups/ali_other_products').then((m) => m.shapes),
  "ali_security": () => import('./groups/ali_security').then((m) => m.shapes),
  "ali_storage_cdn": () => import('./groups/ali_storage_cdn').then((m) => m.shapes),
}
